name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (venv)
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install sysstat (for pidstat)
        run: sudo apt-get update && sudo apt-get install -y sysstat

      - name: Run tests with monitoring
        run: |
          source venv/bin/activate
          echo "=== Start Monitoring ==="
          pidstat -u -r -h 1 30 > pidstat_report.txt &
          MON_PID=$!

          pytest -q

          kill $MON_PID || true
          echo "=== Monitoring Finished ==="

      - name: Upload monitoring report
        uses: actions/upload-artifact@v3
        with:
          name: pidstat-report
          path: pidstat_report.txt
