name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (venv)
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check system resources (before tests)
        run: |
          echo "=== CPU & Memory BEFORE ==="
          top -b -n 1 | head -20
          free -h

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest -q

      - name: Check system resources (after tests)
        run: |
          echo "=== CPU & Memory AFTER ==="
          top -b -n 1 | head -20
          free -h
