name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (venv)
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install monitoring tools
        run: |
          sudo apt-get update
          sudo apt-get install -y sysstat time procps

      - name: Run tests with monitoring
        run: |
          source venv/bin/activate
          echo "=== Mulai testing dengan monitoring ==="
          # Coba pakai pidstat, kalau tidak ada fallback ke time
          if command -v pidstat > /dev/null; then
            echo "Pidstat tersedia, monitoring dengan pidstat..."
            pidstat -u -r -h 1 10 > pidstat_report.txt &
            pytest -q
          else
            echo "Pidstat tidak tersedia, fallback pakai /usr/bin/time..."
            /usr/bin/time -v pytest -q 2> time_report.txt
          fi

      - name: Upload monitoring report
        uses: actions/upload-artifact@v3
        with:
          name: monitoring-report
          path: |
            pidstat_report.txt
            time_report.txt
          if-no-files-found: ignore
