name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (venv)
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install monitoring tools
        run: |
          sudo apt-get update
          sudo apt-get install -y sysstat procps

      - name: Run tests with CPU & Memory monitoring
        run: |
          source venv/bin/activate
          # Jalankan pidstat tiap 1 detik selama 20 detik, rekam CPU & Memory
          pidstat -u -r -h 1 20 > pidstat_report.txt &
          PIDSTAT_PID=$!
          pytest -q
          kill $PIDSTAT_PID || true

      - name: Upload monitoring report
        uses: actions/upload-artifact@v3
        with:
          name: monitoring-report
          path: pidstat_report.txt
